openapi: 3.0.0,
info:
  version: "1.0.0"
  title: "User API"
  description: "API to manage user information"
basePath: "/"
schemes:
  - "http"
paths:
  /user/allUsers:
    get:
      summary: "Get all users"
      description: "Returns a list of all users"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "integer"
                firstName:
                  type: "string"
                lastName:
                  type: "string"

  /user/oneUsers/{id}:
    get:
      summary: "Get one user"
      description: "Returns a list of one users"
      parameters:
        - in: "path"
          name: "id"
          required: "true"
          description: "Numeric ID required"
          schema:
            type : "integer"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful response"
          scheme: 
            type: "array"
            items:
                type: "object"
                properties:
                  id:
                    type: "integer"
                  firstName:
                    type: "string"
                  lastName:
                    type: "string"

  /user/deleteUser:
    delete:
      summary: "Delete user"
      description: "Delete a users"
      parameters:
        - in: "query"
          name: "id"
          required: "true"
          description: "Numeric ID required"
          schema:
            type : "integer"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful deleted user"
          scheme: 
            type: "array"
            items:
                type: "object"
                properties:
                  id:
                    type: "integer"
                  firstName:
                    type: "string"
                  lastName:
                    type: "string"

  /user/createUser:
    post:
      summary: "create new user"
      description: "Create new User description"
      requestBody:
        description: "User object that needs to be created"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: "string"
                lastName:
                  type: "string"       
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful updated User"
          scheme: 
            type: "array"
            items:
                type: "object"
                properties:
                  id:
                    type: "integer"
                  firstName:
                    type: "string"
                  lastName:
                    type: "string"

  /user/updateUser:
    put:
      summary: "update user"
      description: "update user with id"
      consumes:
        - "application/json"
      parameters:
        - in: "query"
          name: "id"
          type: "integer"
          required: "true"
          schema: 
            type: "integer"
        - in: body
          name: abc
          description: "User object that needs to be created"
          required: true
          schema:
            type: "object"
            properties:
                firstName:
                  type: "string"
                lastName:
                  type: "string"
      produces:
        - "application/json"
      responses: 
        200:
          description: "Successful deleted user"
          scheme: 
            type: "array"
            items:
                type: "object"
                properties:
                  id:
                    type: "integer"
                  firstName:
                    type: "string"
                  lastName:
                    type: "string"              